### ISSUE TITLE
Examples run in Jenkins tests all have one chunk

### ISSUE THREAD

**Issue by nbgl** [data61/anonlink-entity-service#360] opened 2019-04-25 04:06 UTC
This is bad, because parts of the code are not being covered (for example, the merging of results from different chunks).

Possible explanations:
1. Tests are misconfigured to omit big problems
2. Chunking is not working correctly, so everything is one chunk

**Comment by nbgl** [comment] 2019-04-25 04:15
I can’t see anywhere in the tests that tries big problems. I can’t find any test cases or large amounts of test data.

@hardbyte @wilko77 Am I missing anything?

**Comment by wilko77** [comment] 2019-04-26 01:41
I can't remember any tests on big problems. It is very possible, that non of the tests involve chunking.

However, we run a benchmark with size 100k by 100k. This should junk. As it turns out, the benchmark was failing because of the broken junking, but jenkins did not report the failure -> issue #361. 

Instead of including big problems in the tests (which will increase test run time), we could also control the junking size and set it explicitly to something smaller than the input size.

**Comment by nbgl** [comment] 2019-05-07 11:11
Are we satisfied with the current solution (of running the benchmarks)? Or do we want to keep this issue open and implement Wilko’s idea?

**Comment by hardbyte** [comment] 2019-05-08 03:17
I think we should keep the issue open until the integration tests use a smaller chunking size.

A better outcome - involving a lot more work - would be to parameterize various deploy time config options during testing.

**Comment by gusmith** [comment] 2019-07-03 05:18
I've been assigned to the issue, but I'll need some context, are we talking about http chunking?
Where are the current configurations? What is the expected behaviour from nginx? Buffering the whole content, passing it down to the application? Do we want to implement a unit test in which the content in chunked and we mock the underlying services?

**Comment by gusmith** [comment] 2019-07-03 07:32
If this is about the http chunking, it seems to be related to #184, or is it an issue from the client side?

**Comment by hardbyte** [comment] 2020-02-10 02:18
We no longer use Jenkins and our CI tests still include running benchmarking to ensure we try chunking code.

**Closed by hardbyte** 2020-02-10 02:18 UTC
Labels: bug, devops, integration tests
